### ISSUE TITLE
.root files/IAEA phase spaces to MCPL

### ISSUE THREAD

**Issue by Laiba-Zahra** [mctools/mcpl#74]
Hey!
        I am using GATE (Geant4 extension) to write phase space files and want to import these files into another monte carlo code i.e. OpenMC. Since GATE can read/write files of types .root and IAEA phase space files, whereas for OpenMC it reads MCPL files, but I couldn't find an MCPL hook for GATE.

**Comment by tkittel** [comment]
So this involves both the reading of GATE files and the writing of MCPL files. The latter we can help with, but the best avenue of approach here is if a GATE-file-format expert would get involved in regards to the former. Because not only do we need to know what is in the files produced by GATE, but it is also beneficial if there is awareness of an eventual gate2mcpl utility in the GATE community - to prevent the utility being obsoleted by changes on the GATE side of things.

Let us know if you are that expert, or if you manage to persuade someone to get involved.

**Comment by tkittel** [comment]
I am going to close here, please open a new issue if there is some progress.
